IsTrustedSequencer = true

[Log]
Level = "debug"
Outputs = ["stdout"]

[Database]
User = "test_user"
Password = "test_password"
Name = "test_db"
Host = "zkevm-db"
Port = "5432"
EnableLog = false
MaxConns = 200

[Etherman]
URL = "http://zkevm-mock-l1-network:8545"
PrivateKeyPath = "./test/test.keystore"
PrivateKeyPassword = "testonly"

[RPC]
Host = "0.0.0.0"
Port = 8123
MaxRequestsPerIPAndSecond = 5000
SequencerNodeURI = ""
BroadcastURI = "127.0.0.1:61090"

[Synchronizer]
SyncInterval = "1s"
SyncChunkSize = 100
TrustedSequencerURI = ""

[Sequencer]
WaitPeriodPoolIsEmpty = "15s"
LastBatchVirtualizationTimeMaxWaitPeriod = "15s"
WaitBlocksToUpdateGER = 10
LastTimeBatchMaxWaitPeriod = "15s"
BlocksAmountForTxsToBeDeleted = 100
FrequencyToCheckTxsForDelete = "12h"
	[Sequencer.ProfitabilityChecker]
		SendBatchesEvenWhenNotProfitable = "true"

[Aggregator]
IntervalToConsolidateState = "10s"
IntervalFrequencyToGetProofGenerationStateInSeconds = "5s"
TxProfitabilityCheckerType = "acceptall"
TxProfitabilityMinReward = "1.1"

[GasPriceEstimator]
Type = "default"
DefaultGasPriceWei = 1000000000

[Prover]
ProverURI = "zkevm-prover:50052"

[MTServer]
Host = "0.0.0.0"
Port = 50060
StoreBackend = "PostgreSQL"

[MTClient]
URI  = "zkevm-prover:50061"

[Executor]
URI = "zkevm-prover:50071"

[BroadcastServer]
Host = "0.0.0.0"
Port = 61090
