---
name: Update dependencies
on:
  schedule:
    - cron:  '* */6 * * *'
  workflow_dispatch:
jobs:
  updatedeps:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744

    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.21.x"
      env:
        GOARCH: "amd64"

    - name: Install Protoc
      uses: arduino/setup-protoc@v1

    - name: Install protoc-gen-go
      run: |
        go install github.com/golang/protobuf/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

    - name: Update deps
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: make update-external-dependencies

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        commit-message: update external dependencies
        title: Update external dependencies
        body: Check for new images, test vectors and proto files and update the code to use them.
        branch: update-external-dependencies
        base: develop
        author: int-bot <int-bot@users.noreply.github.com>
        committer: int-bot <int-bot@users.noreply.github.com>
